export const AMAZON_CATEGORIES = {
  "Appliances": [
    "Refrigerators",
    "Freezers",
    "Washers & Dryers",
    "Parts & Accessories",
    "Cooking Ranges",
    "Dishwashers"
  ],
  "Arts, Crafts & Sewing": [
    "Painting, Drawing & Art Supplies",
    "Beading & Jewelry Making",
    "Crafting",
    "Fabric",
    "Sewing",
    "Needlework"
  ],
  "Automotive": [
    "Car Care",
    "Car Electronics & Accessories",
    "Exterior Accessories",
    "Interior Accessories",
    "Lights & Lighting Products",
    "Motorcycle & Powersports",
    "Oils & Fluids",
    "Paint & Paint Supplies",
    "Performance Parts & Accessories",
    "Replacement Parts",
    "RV Parts & Accessories",
    "Tires & Wheels",
    "Tools & Equipment"
  ],
  "Baby Products": [
    "Activity & Entertainment",
    "Apparel & Accessories",
    "Baby & Toddler Toys",
    "Baby Care",
    "Car Seats & Accessories",
    "Diapering",
    "Feeding",
    "Gifts",
    "Nursery",
    "Potty Training",
    "Pregnancy & Maternity",
    "Safety",
    "Strollers & Accessories",
    "Travel Gear"
  ],
  "Beauty & Personal Care": [
    "Makeup",
    "Skin Care",
    "Hair Care",
    "Fragrance",
    "Foot, Hand & Nail Care",
    "Tools & Accessories",
    "Shave & Hair Removal",
    "Personal Care",
    "Oral Care"
  ],
  "Camera & Photo": [
    "Cameras",
    "Lenses",
    "Accessories",
    "Camcorders",
    "Video Surveillance",
    "Binoculars & Scopes",
    "Lighting & Studio"
  ],
  "Cell Phones & Accessories": [
    "Cell Phones",
    "Cases, Holsters & Sleeves",
    "Accessories",
    "Unlocked Cell Phones",
    "SIM Cards & Prepaid Minutes"
  ],
  "Computers & Accessories": [
    "Laptops",
    "Desktops",
    "Monitors",
    "Computer Components",
    "Drives & Storage",
    "Accessories",
    "Networking",
    "Printers",
    "Scanners",
    "Servers",
    "Tablet Accessories"
  ],
  "Electronics": [
    "Accessories & Supplies",
    "Camera & Photo",
    "Car & Vehicle Electronics",
    "Cell Phones & Accessories",
    "Computers & Accessories",
    "GPS & Navigation",
    "Headphones",
    "Home Audio",
    "Office Electronics",
    "Portable Audio & Video",
    "Security & Surveillance",
    "Service Plans",
    "Television & Video",
    "Video Game Consoles & Accessories",
    "Video Projectors",
    "Wearable Technology"
  ],
  "Grocery & Gourmet Food": [
    "Beverages",
    "Breakfast Foods",
    "Canned, Jarred & Packaged Foods",
    "Coffee, Tea & Beverages",
    "Cooking & Baking",
    "Dairy, Cheese & Eggs",
    "Deli & Prepared Foods",
    "Frozen",
    "Meat & Seafood",
    "Pantry Staples",
    "Produce",
    "Snack Foods"
  ],
  "Health & Household": [
    "Baby & Child Care",
    "Health Care",
    "Household Supplies",
    "Medical Supplies & Equipment",
    "Oral Care",
    "Personal Care",
    "Sexual Wellness",
    "Sports Nutrition",
    "Stationery & Gift Wrapping Supplies",
    "Vision Care",
    "Vitamins & Dietary Supplements",
    "Wellness & Relaxation"
  ],
  "Home & Kitchen": [
    "Bath",
    "Bedding",
    "Cleaning Supplies",
    "Dining & Entertaining",
    "Furniture",
    "Heating, Cooling & Air Quality",
    "Home Décor",
    "Irons & Steamers",
    "Kids' Home Store",
    "Kitchen & Dining",
    "Lighting & Ceiling Fans",
    "Seasonal Décor",
    "Storage & Organization",
    "Vacuums & Floor Care",
    "Wall Art",
    "Window Treatments"
  ],
  "Industrial & Scientific": [
    "Abrasive & Finishing Products",
    "Additive Manufacturing",
    "Commercial Door Products",
    "Cutting Tools",
    "Fasteners",
    "Filtration",
    "Food Service Equipment & Supplies",
    "Hydraulics, Pneumatics & Plumbing",
    "Industrial Electrical",
    "Industrial Hardware",
    "Industrial Power & Hand Tools",
    "Janitorial & Sanitation Supplies",
    "Lab & Scientific Products",
    "Material Handling",
    "Occupational Health & Safety Products",
    "Packaging & Shipping Supplies",
    "Power Transmission Products",
    "Professional Medical Supplies",
    "Raw Materials",
    "Retail Store Fixtures & Equipment",
    "Robotics",
    "Science Education",
    "Tapes, Adhesives & Sealants",
    "Test, Measure & Inspect"
  ],
  "Office Products": [
    "Office Electronics",
    "Office Furniture & Lighting",
    "Office Supplies",
    "School Supplies"
  ],
  "Patio, Lawn & Garden": [
    "Farm & Ranch",
    "Gardening & Lawn Care",
    "Generators & Portable Power",
    "Grills & Outdoor Cooking",
    "Outdoor Décor",
    "Outdoor Furniture & Accessories",
    "Outdoor Heating",
    "Outdoor Lighting",
    "Outdoor Storage",
    "Patio Furniture & Accessories",
    "Pest Control",
    "Plant Support Structures",
    "Plants, Seeds & Bulbs",
    "Pools, Hot Tubs & Supplies",
    "Snow Removal",
    "Watering Equipment"
  ],
  "Pet Supplies": [
    "Birds",
    "Cats",
    "Dogs",
    "Fish & Aquatic Pets",
    "Horses",
    "Insects",
    "Reptiles & Amphibians",
    "Small Animals"
  ],
  "Sports & Outdoors": [
    "Outdoor Recreation",
    "Sports & Fitness",
    "Fan Shop"
  ],
  "Tools & Home Improvement": [
    "Appliances",
    "Building Supplies",
    "Electrical",
    "Hardware",
    "Kitchen & Bath Fixtures",
    "Light Bulbs",
    "Lighting & Ceiling Fans",
    "Measuring & Layout Tools",
    "Painting Supplies & Wall Treatments",
    "Power & Hand Tools",
    "Rough Plumbing",
    "Safety & Security",
    "Storage & Home Organization",
    "Welding & Soldering"
  ],
  "Toys & Games": [
    "Action Figures & Statues",
    "Arts & Crafts",
    "Building Toys",
    "Dolls & Accessories",
    "Electronics for Kids",
    "Games",
    "Hobbies",
    "Kids' Furniture, Décor & Storage",
    "Learning & Education",
    "Novelty & Gag Toys",
    "Party Supplies",
    "Puppets",
    "Puzzles",
    "Sports & Outdoor Play",
    "Stuffed Animals & Plush Toys",
    "Toy Vehicles",
    "Tricycles, Scooters & Wagons"
  ],
  "Video Games": [
    "PlayStation 5",
    "PlayStation 4",
    "Xbox Series X & S",
    "Xbox One",
    "Nintendo Switch",
    "PC",
    "Mac",
    "Legacy Systems",
    "Microconsoles",
    "Virtual Reality"
  ]
};